---
deployment:
  tasks:
    - /bin/cp -Rfv dist/* /home/kumonwah/public_html/
    - /bin/cp -fv dist/.htaccess /home/kumonwah/public_html/
    - /bin/mkdir -p /home/kumonwah/public_html/api
    - /bin/cp -Rfv api/* /home/kumonwah/public_html/api/
    - /bin/cp -fv api/.htaccess /home/kumonwah/public_html/api/
