---
deployment:
  tasks:
    - /bin/cp -Rf dist/* /home/kumonwah/public_html/
    - /bin/cp -f dist/.htaccess /home/kumonwah/public_html/
    - /bin/mkdir -p /home/kumonwah/public_html/api
    - /bin/cp -Rf api/* /home/kumonwah/public_html/api/
    - /bin/cp -f api/.htaccess /home/kumonwah/public_html/api/
